### ISSUE TITLE
Inconsistent reference to config file

### ISSUE THREAD

**Issue by lepisma** [mihaiolteanu/lastfm#3]
Hi, thanks for this great library!

I was trying to use this for something and realized that the main config file (with credentials) is referred differently in three places:

1. In README it's `~/.lastfmrc`
2. In `#'config` it's effectively `~/.config/.lastfmrc`
    https://github.com/mihaiolteanu/lastfm/blob/cc2d0cf96cb5112d5759080548003fec636ff8f6/lastfm.lisp#L18
3. In `#'add-sk-to-rcfile` it is hardcoded as `~/.config/.lastfm.lisp`
    https://github.com/mihaiolteanu/lastfm/blob/cc2d0cf96cb5112d5759080548003fec636ff8f6/lastfm.lisp#L105

Would be nice to make them the same.

PS: I am assuming you have it working locally so not doing a pull request.

**Comment by mihaiolteanu** [comment]
Hei. I was off in vacation for some time. Sorry for the late reply.
Yes, I've changed the location for the config file several times. It seems I haven't updated all the places that reference this file. I will have a look.

Thanks for your input! I will have a look at your PRs also. 

I hope this library works for you otherwise.

**Comment by mihaiolteanu** [comment]
Fixed with `cebf1d8`
